# Create docker image ..

# .. from existing PHP image version 7.2, containing apache
FROM php:7.2-apache

# And copy our content/ folder into the position where the docker uses its ressources
COPY content/ /var/www/html/

