
version: "3.9"

services:
    # ******************************* #
    static:
        build: ./../step4/static/.
        #container_name: dai_http_step1
        ports:
            #- "9002:80"
            - "80"
        labels:
            - traefik.autodetect=true
            #router: static
            - traefik.http.routers.static.rule=Host(`localhost`)
            #- traefik.http.routers.static.entryPoints=static_server

    # ******************************* #
    dynamic:
        build: ./../step4/dynamic/.
        #container_name: dai_http_step2
        ports:
            #- "9003:3000"
            - "3000"
        labels:
            - traefik.autodetect=true
            #router: dynamic
            - traefik.http.routers.dynamic.rule=(Host(`localhost`) && PathPrefix(`/api`))
            #- traefik.http.routers.dynamic.entryPoints=dynamic_server

    # ******************************* #
    # Ref: https://jacar.es/en/como-instalar-portainer-con-docker-compose/
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./portainer-data:/data
        ports:
            #- 9001:9000
            - 9000
        labels:
            - traefik.autodetect=true
            - traefik.http.routers.portainer.rule=(Host(`localhost`) && PathPrefix(`/ui`))

    # ******************************* #
    reverse-proxy:
        # The official v2 Traefik docker image
        image: traefik:v2.9
        # Enables the web UI and tells Traefik to listen to docker
        command: --api.insecure=true --providers.docker
        ports:
            - "80:80"       # The HTTP port
            - "9000:8080"   # The Web UI (enabled by --api.insecure=true)
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock

