version: "3.9"
services:
    # ******************************* #
    static:
        build: ./static/.
        deploy:
            replicas: 3
        ports:
            - "80"
        labels:
            - traefik.autodetect=true
            - traefik.http.routers.static.rule=Host(`localhost`)
            # sticky session
            - traefik.http.services.static.loadbalancer.sticky.cookie=true
            - traefik.http.services.static.loadbalancer.sticky.cookie.name=static-cookie

    # ******************************* #
    dynamic:
        build: ./dynamic/.
        deploy:
            replicas: 3
        ports:
            - "3000"
        labels:
            - traefik.autodetect=true
            - traefik.http.routers.dynamic.rule=(Host(`localhost`) && PathPrefix(`/api`))

    # ******************************* #
    whoami:
        # A container that exposes an API to show its IP address
        image: traefik/whoami
        deploy:
            replicas: 3
        labels:
            - traefik.autodetect=true
            - traefik.http.routers.whoami.rule=(Host(`localhost`) && PathPrefix(`/ip`))
            # sticky session
            - traefik.http.services.whoami.loadbalancer.sticky.cookie=true
            - traefik.http.services.whoami.loadbalancer.sticky.cookie.name=whoami-cookie

    # ******************************* #
    reverse-proxy:
        # The official v2 Traefik docker image
        image: traefik:v2.9
        # Enables the web UI and tells Traefik to listen to docker
        command:
            --api.insecure=true --providers.docker

        ports:
#            - "80:80"       # The HTTP port
            - "8999:8080"   # The Web UI (enabled by --api.insecure=true)
            # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
            -   target: 80
                published: 80
                mode: host
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
